version: '3'
services:
  rso-stats:
    container_name: rso-stats
    image: stats:latest
    ports:
      - "8082:8082"
    environment:
      - KUMULUZEE_SERVER_BASEURL=http://${DOCKER_HOST_IP}:8082
    depends_on:
      - "stats-db"
  stats-db:
    container_name: rso-stats-db
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rso-stats