apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgre
  labels:
    app: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - image: postgres:latest
          name: postgre
          env:
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: rso-stats
          ports:
            - containerPort: 5432
              name: postgre
          volumeMounts:
            - name: persistant-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: persistant-storage
          persistentVolumeClaim:
            claimName: postgresql-volume