apiVersion: v1
kind: Service
metadata:
  labels:
    app: stats
  name: stats
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: stats