kumuluzee:
  name: rso-stats
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://172.17.0.1:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/StatsDS
#      connection-url: jdbc:postgresql://localhost:5433/rso-stats
      connection-url: jdbc:postgresql://172.17.0.1:5433/rso-stats
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://172.17.0.1:2379
    ttl: 20
    ping-interval: 15