kumuluzee:
  name: rso-stats
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://172.17.0.1:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/StatsDS
#      connection-url: jdbc:postgresql://localhost:5433/rso-stats
      connection-url: jdbc:postgresql://172.17.0.1:5433/rso-stats
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://172.17.0.1:2379
    ttl: 20
    ping-interval: 15
  logs:
        config-file:
          '<?xml version="1.0" encoding="UTF-8"?>
           <Configuration name="stats">
               <Appenders>
                   <Console name="console" target="SYSTEM_OUT">
                       <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                   </Console>

                   <!-- A socket definition for sending logs into Logstash using TCP and JSON format.-->
                   <!-- 14-day trial -->
                   <Socket name="logstash" host="5c736c1f-93bb-494f-9fd0-f2564e8bbd74-ls.logit.io" port="20760" protocol="tcp">
                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                   </Socket>
               </Appenders>
               <Loggers>
                   <!-- Resources (REST) -->
                   <Logger name="si.fri.rso.team10.ListenResource" level="trace" additivity="false">
                       <AppenderRef ref="console"/>
                       <AppenderRef ref="logstash"/>
                   </Logger>

                   <Logger name="si.fri.rso.team10.UploadResource" level="trace" additivity="false">
                       <AppenderRef ref="console"/>
                       <AppenderRef ref="logstash"/>
                   </Logger>

                   <!-- Default logger -->
                   <Root level="info">
                       <AppenderRef ref="console"/>
                       <AppenderRef ref="logstash"/>
                   </Root>
               </Loggers>
           </Configuration>'